# node.js image
FROM node:18-alpine

# working directory
WORKDIR /app

# install bash
RUN apk add --no-cache bash

# copy files
COPY package*.json ./

# install dependencies
RUN npm ci --only=production && npm cache clean --force

# copy code
COPY . .

# Set permissions for submit.sh
RUN chmod +x app/_private/utils/submit.sh

# build application
RUN npm run next:build

# expose port
EXPOSE 3000

# start application
CMD ["npm", "run", "next:start"] 