const dashboardConstants = {
  CREATE_SIMULATION: 'CREATE_SIMULATION',
  READ_ALL_SIMULATIONS: 'READ_ALL_SIMULATIONS',
  UPDATE_SIMULATION: 'UPDATE_SIMULATION',
  DELETE_SIMULATION: 'DELETE_SIMULATION',
};

export default dashboardConstants;
