# node.js image
FROM node:slim

# working directory
WORKDIR /app

# install bash
RUN apk add --no-cache bash

# copy files
COPY package*.json ./

# install dependencies
RUN npm ci

# copy code
COPY . .

# Set permissions for submit.sh
RUN chmod +x app/_private/utils/submit.sh

# build application
RUN npx next build

# remove dev dependencies
RUN npm prune --production

# expose port
EXPOSE 3000

# start application
CMD ["npx", "next", "start"] 